# Generated by Django 5.2.13 on 2026-04-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_rename_notification_recipient_unread_notificatio_recipie_8bedf2_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='data'),
        ),
    ]
