# Generated by Django 5.2.13 on 2026-04-12 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0011_replace_jsonfield_with_native'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['actor_content_type', 'actor_object_id'], name='notificatio_actor_c_4f870b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='notificatio_target__dfbaf5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['action_object_content_type', 'action_object_object_id'], name='notificatio_action__6e12f7_idx'),
        ),
    ]
